name: indoor_navigation_app
description: "실내 네비게이션 앱"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  #sdk: ^3.10.8
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ar_flutter_plugin_2: ^0.0.3
  camera: ^0.11.3
  camera_intrinsics: ^0.0.4
  permission_handler: ^11.3.1
  vector_math: ^2.1.4
  http: ^1.1.2
  image: ^4.1.3
  intl: ^0.18.0
  provider: ^6.1.1
  sensors_plus: ^7.0.0
  webview_flutter: ^4.4.2
  url_launcher: ^6.2.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

